name: Run Groupsor Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC (24-hour interval)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python Script
      run: |
        python groupsor_request.py
        
